/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package linkedlist;



public class App {


    public static void main(String[] args) {
        LinkedList myLinkedList = new LinkedList();

        myLinkedList.insert(1);
        myLinkedList.insert(2);
        myLinkedList.insert(3);

        StringBuilder myResult = new StringBuilder();
        myResult = myLinkedList.toStringA();
        System.out.println(myResult.toString());


    }
}
