/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertion;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        int[] myTestArray = {8,4,23,42,16,15};
        InsertionSort myInsertion = new InsertionSort();

        myInsertion.insertionSort(myTestArray);

    }
}
