/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedlist;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
    }

    @Test
    void createEmptyLinkedList() {
        // Arrange
        LinkedList teskLinkedList = new LinkedList();
        Node mytestNode = new Node(5);

        //assert
        assertTrue(teskLinkedList.head == null, "Condition met passed Test emptyArray created");
    }

    //edge case for ensuring empty array list is generated
    @Test
    void testEmptyListEdgeCase() {
        //Arrange
        LinkedList teskLinkedList = new LinkedList();
        Node mytestNode = new Node(5);
        assertFalse(teskLinkedList.head == mytestNode, "Passed test ?");
    }

    @Test
    void checkInsertToLinkedList() {
        LinkedList testLinkedList = new LinkedList();
        testLinkedList.insert(5);
        assertTrue(testLinkedList.head.value == 5, "value and Node is there");
    }

    @Test
    void insertToLinkedLits() {
        LinkedList testLinkedList = new LinkedList();
        testLinkedList.insert(10);

        assertTrue(testLinkedList.head.value == 10, "inserted to linked list ");

    }

    @Test
    void checkValue() {
        LinkedList testLinkedList = new LinkedList();
        testLinkedList.insert(5);
        testLinkedList.insert(10);
        assertFalse(testLinkedList.includes(5));
    }

    //Test with multiple to the end
    @Test
    void checkAddMultipletoEnd(){
        LinkedList myLinkedList = new LinkedList();

        myLinkedList.insert(1);
        myLinkedList.insert(2);
        myLinkedList.insert(3);
        myLinkedList.insert(5);
        myLinkedList.insert(8);

        myLinkedList.insertAfter(10,11);
        myLinkedList.insertAfter(11,12);
        StringBuilder myOtherResult = new StringBuilder();
        myOtherResult = myLinkedList.toStringA();

        String resutl = "{ 1 }->{ 2 }->{ 3 }->{ 5 }->{ 8 }->{ 11 }->{ 12 }->";

        assertTrue(resutl.equals(myOtherResult.toString()));


    }

    @Test
    void addToMiddle(){
        LinkedList myLinkedList = new LinkedList();

        myLinkedList.insert(1);
        myLinkedList.insert(2);
        myLinkedList.insert(3);
        myLinkedList.insert(5);
        myLinkedList.insert(8);
        myLinkedList.insert(9);

        myLinkedList.insertAfter(3,100);
        StringBuilder myOtherResult = new StringBuilder();
        myOtherResult = myLinkedList.toStringA();


        String myExpectedResult = "{ 1 }->{ 2 }->{ 3 }->{ 100 }->{ 5 }->{ 8 }->{ 9 }->";

        assertTrue(myExpectedResult.equals(myOtherResult.toString()));
    }

    //passed but getting random error
    @Test
    void checkStrings() {
        LinkedList testLinkedList = new LinkedList();
        testLinkedList.insert(1);
        testLinkedList.insert(2);
        testLinkedList.insert(3);
        StringBuilder result = testLinkedList.toStringA();
        String expectedResult = "{ a }->{ b }->{ c }->";

        assertTrue(expectedResult.equals(result.toString()));
    }

}

